http:
  listener:
    host: "localhost"
    port: "8082"
    path: "/fastGoCall/{serviceType}"

db:
  mysql:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "Shekar@492"
    database: "busservices"